### ISSUE TITLE
Display multiple chats on teachers page

### ISSUE THREAD

**Issue by mssiegel** [Frempco/web-client#4]
Teachers want the ability to see several different chats simultaneously. This will let them better monitor what the students are doing. Currently they can only see a single displayed chat. 

We should add some sort of view on the teachers page showing multiple chats at once. 

Below are my suggestions for the user design. But feel free to use whatever user design you prefer. The user design doesn't have to be perfect. We can just get it up and out there and improve the design later.

UX suggestions:
- the mutliple chats should be on the bottom of the teachers classroom  page
- it should not have any buttons
- each chat should just show the most recent 4-5 lines

Lets put it under the paired students list as it grants the widest view of the multiple chats.

**Comment by leahnp613** [comment]
How high priority is this?

**Comment by karlrez** [comment]
I'll take this one on, @leahnp613 if you already made a start you're free to take it as well.

I think i'll just hard code in two rows of chats and make a minor PR for the UI, and then work on displaying the actual chats afterwards

**Comment by leahnp613** [comment]
Thanks, I’ve just been in 6 different places mentally. I had an interview this week.
