### ISSUE TITLE
Teacher can copy displayed chat

### ISSUE THREAD

**Issue by mssiegel** [Frempco/web-client#6]
Students have a button on their page which lets them copy their chat.
We should add a similar button on the Teachers page. This button would go above the displayed chat and would copy it.

For this task, you can probably just reuse the button on the student's page. To avoid duplicated code, you can extract the copy functionality into its own reusuable utility function or React Component.

Having this button would enable teachers to save any student chat. This has many benefits. For example, it would let the teacher copy/paste any chat into a Google Doc and edit it in real-time in full view of the students. As the teacher edits the chat, they can explain to students why they're making the edits they are.

**Comment by rblcoder** [comment]
@mssiegel 
We have the component CopyButton.tsx. 

Would this be a possible implementation - We can move CopyButton.tsx to components/shared and use it in both StudentsPage and TeachersPage?
There would be no changes needed in CopyButton.tsx, right?

**Comment by mssiegel** [comment]
Thanks so much for taking this rblcoder! I'll defer to @zachlankton 
Previously, I was answering technical questions. But I'm handing off that responsibility to Zach as he has a deeper understanding of our codebase.
I often speak to the school teachers who use our learning platform.  So product level questions and questions about our customer's needs should still go to me.

**Comment by zachlankton** [comment]
@rblcoder that sounds like a fantastic idea! I say go for it!

**Comment by rblcoder** [comment]
Thanks @mssiegel and @zachlankton for your encouragement, I tried an implementation, I am unable to copy chat as a Teacher, The clipboard remains unchanged when I try to copy chat as a Teacher.

**Comment by zachlankton** [comment]
@rblcoder I just tried you code and it is working for me, can you try again?

**Comment by mssiegel** [comment]
By the way, rblcoder I feel the id on teacher's page should be named 'displayed-chat'. Although on student's page it could remain just 'conversation' as students page only has a single conversation.

**Comment by rblcoder** [comment]
@zachlankton I see now that I am able to copy when using browsers apart from firefox. @mssiegel I have made the change you have mentioned.

**Comment by mssiegel** [comment]
Thanks @rblcoder.  Frempco is just being used with a small beta testing set of 3-5 american school teachers who are giving us feedback. They've told me that American schools typically provide their students with chromebooks. So the students use chrome.  the teachers therefore also typically use chrome in the classroom.  So we don't support firefox now.

**Comment by rblcoder** [comment]
@mssiegel Got it. 
Is it fine to merge this?

**Comment by mssiegel** [comment]
The PR looked good to me. But I'm deferring to Zach as I'm handing off technical supervision to him.   That being said, @rblcoder can you add a screenshot to the conversation. That way we'll able to see the UI and approve without having to run it locally.  See example PR from our old repo: https://github.com/mssiegel/frempco-client/pull/141

Only desktop screenshot is needed because teachers would never use mobile as its too small for them.  Thanks so much for all you're helping out with!

**Comment by mssiegel** [comment]
@rblcoder I just merged your copy-chat PR! Thanks so much!   Do you plan to continue contributing on a regular basis?  If so, we can add you as a collaborator to this repo. That'll make it easier for you to make PRs directly. We could also add you to our Slack workspace.

**Comment by mssiegel** [comment]
Also, @rblcoder if you'd like to know about the history of Frempco and where we're headed feel free to connect/follow me.   I post daily videos about our journey on LinkedIn and on Youtube.
LinkedIn: https://www.linkedin.com/in/moshesiegel/
YouTube: https://www.youtube.com/@MosheSiegel

**Comment by rblcoder** [comment]
@mssiegel I am looking at which issue I can pick up next. I am thinking will I be able to contribute more or will I get stuck.
